<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/01/25 22:35:02
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
